/* Automatically generated by './build/build-entries.js (thanks element-ui)' */
/* eslint-disable */
import { VueConstructor } from "vue/types/umd";

import MazDropzone from "./components/MazDropzone/index.vue";
import MazPlotly from "./components/MazPlotly/index.vue";
import { version } from "../package.json";

const components = [MazDropzone, MazPlotly];

const install = (Vue: VueConstructor, opts = {}) => {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

if (typeof window !== "undefined" && window.Vue) {
  install(window.Vue);
}

export default {
  version,
  install,
  MazDropzone,
  MazPlotly
};

export { version, install };
/* eslint-enable */
