/* Automatically generated by './build/build-entries.js (thanks element-ui)' */
/* eslint-disable */

import { VueConstructor } from "vue/types/umd";

import MazAvatar from "./components/MazAvatar/index.vue";
import MazBottomSheet from "./components/MazBottomSheet/index.vue";
import MazBtn from "./components/MazBtn/index.vue";
import MazBtnGroup from "./components/MazBtnGroup/index.vue";
import MazCard from "./components/MazCard/index.vue";
import MazCarousel from "./components/MazCarousel/index.vue";
import MazCheckbox from "./components/MazCheckbox/index.vue";
import MazCollapse from "./components/MazCollapse/index.vue";
import MazDialog from "./components/MazDialog/index.vue";
import MazDraggableList from "./components/MazDraggableList/index.vue";
import MazDropdown from "./components/MazDropdown/index.vue";
import MazFlex from "./components/MazFlex/index.vue";
import MazGallery from "./components/MazGallery/index.vue";
import MazImg from "./components/MazImg/index.vue";
import MazInput from "./components/MazInput/index.vue";
import MazInputTags from "./components/MazInputTags/index.vue";
import MazList from "./components/MazList/index.vue";
import MazListItem from "./components/MazList/MazListItem/index.vue";
import MazLoader from "./components/MazLoader/index.vue";
import MazPagination from "./components/MazPagination/index.vue";
import MazPicker from "./components/MazPicker/index.vue";
import MazProgressBar from "./components/MazProgressBar/index.vue";
import MazPhoneNumberInput from "./components/MazPhoneNumberInput/index.vue";
import MazRadio from "./components/MazRadio/index.vue";
import MazReadMore from "./components/MazReadMore/index.vue";
import MazResponsiveMenu from "./components/MazResponsiveMenu/index.vue";
import MazSearch from "./components/MazSearch/index.vue";
import MazSelect from "./components/MazSelect/index.vue";
import MazSidebar from "./components/MazSidebar/index.vue";
import MazSlider from "./components/MazSlider/index.vue";
import MazSpinner from "./components/MazSpinner/index.vue";
import MazStepper from "./components/MazStepper/index.vue";
import MazSwitch from "./components/MazSwitch/index.vue";
import MazTabsBar from "./components/MazTabsLayout/MazTabsBar/index.vue";
import MazTabsContent from "./components/MazTabsLayout/MazTabsContent/index.vue";
import MazTabsContentItem from "./components/MazTabsLayout/MazTabsContentItem/index.vue";
import MazTransitionExpand from "./components/MazTransitionExpand/index.vue";
import { version } from "../package.json";

const components = [
  MazAvatar,
  MazBottomSheet,
  MazBtn,
  MazBtnGroup,
  MazCard,
  MazCarousel,
  MazCheckbox,
  MazCollapse,
  MazDialog,
  MazDraggableList,
  MazDropdown,
  MazFlex,
  MazGallery,
  MazImg,
  MazInput,
  MazInputTags,
  MazList,
  MazListItem,
  MazLoader,
  MazPagination,
  MazPicker,
  MazProgressBar,
  MazPhoneNumberInput,
  MazRadio,
  MazReadMore,
  MazResponsiveMenu,
  MazSearch,
  MazSelect,
  MazSidebar,
  MazSlider,
  MazSpinner,
  MazStepper,
  MazSwitch,
  MazTabsBar,
  MazTabsContent,
  MazTabsContentItem,
  MazTransitionExpand
];

const install = (Vue: VueConstructor, opts = {}) => {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

if (typeof window !== "undefined" && window.Vue) {
  install(window.Vue);
}

export default {
  version,
  install,
  MazAvatar,
  MazBottomSheet,
  MazBtn,
  MazBtnGroup,
  MazCard,
  MazCarousel,
  MazCheckbox,
  MazCollapse,
  MazDialog,
  MazDraggableList,
  MazDropdown,
  MazFlex,
  MazGallery,
  MazImg,
  MazInput,
  MazInputTags,
  MazList,
  MazListItem,
  MazLoader,
  MazPagination,
  MazPicker,
  MazProgressBar,
  MazPhoneNumberInput,
  MazRadio,
  MazReadMore,
  MazResponsiveMenu,
  MazSearch,
  MazSelect,
  MazSidebar,
  MazSlider,
  MazSpinner,
  MazStepper,
  MazSwitch,
  MazTabsBar,
  MazTabsContent,
  MazTabsContentItem,
  MazTransitionExpand
};

export { version, install };
/* eslint-enable */
